apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vote
  name: vote
  namespace: vote-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31337
  selector:
    app: vote
  type: NodePort
status:
  loadBalancer: {}
