apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: vote-app
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
   path: /data/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: vote-app
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
